project: ivtlr
save_path: /path/IVT-LR/qwen_vl/
name: qwen_base_scienceqa
model_id: Qwen/Qwen2-VL-7B-Instruct

seed: 0
resume: 0
bf16: True
batch_size_training: 2
debug: False
gradient_accumulation_steps: 8
num_epochs: 16
lr: !!float "4e-5"
